apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: my-nginx
  ports:
  - port: 8888
    targetPort: 80

